name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/wesmania/game-life-report-docker:docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build the docs
        run: |
          make html
          make latexpdf
      - name: Zip up html
        run: |
          cd build
          zip -r game-life-report-html.zip html
      - name: Save html artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-life-report-html
          path: build/game-life-report-html.zip
      - name: Save pdf artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-life-report-pdf
          path: build/latex/game-life-report.pdf
      - name: Publish docs to github pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
          force_orphan: true

  link-artifacts:
    runs-on: ubuntu-latest
    needs: build-docs
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Publish artifact links
        uses: beni69/artifact-link@v1
        if: ${{ github.event_name == 'pull_request'}}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
